### ISSUE TITLE
Moving to `grunt-assemble-navigation`

### ISSUE THREAD

**Issue by doowb** [assemble/grunt-assemble-navigation#2]
I'll be moving the `grunt-assemble` version of this code to `grunt-assemble-navigation` and deprecating `assemble-middleware-navigation` on npm. If anyone has any issues/questions/comments, please leave them here so we may discuss.

**Comment by jonschlinkert** [comment]
:+1:

**Comment by doowb** [comment]
Done.

- [x] tagged code snapshot before moving to `grunt-assemble-navigation`
- [x] reverted code to `grunt-assemble`
- [x] published `grunt-assemble-navigation`
- [x] renamed repository to `grunt-assemble-navigation`
